searchfragment + radiobuttons
CMPUT301W23T22/QRCodesForNoobs pull request #55
Opened 2023-03-08 21:56 UTC by invindus

<img width="259" alt="image" src="https://user-images.githubusercontent.com/73728946/223859573-43d9404c-3397-4802-8989-39ec554361b0.png"><img width="266" alt="image" src="https://user-images.githubusercontent.com/73728946/223859608-0d1ff4f6-3d6a-4926-8a4a-0fba5f6d026e.png">

2023-03-08 23:16 UTC, sepniojr approved these changes

2023-03-09 04:48 UTC, thomassuu approved these changes

2023-03-09 06:12 UTC, guerrapavez commented on code/app/src/main/java/com/example/qrcodesfornoobs/Fragment/SearchFragment.java
> +                            searchList.add(str);
use firebase query?

2023-03-09 22:08 UTC, thomassuu reviewed
crashing...

2023-03-09 22:11 UTC, thomassuu requested changes
please check your branch again as it's crashing on my side

2023-03-10 03:23 UTC, closed without merging

2023-03-10 03:24 UTC, invindus commented
rewriting SearchFragment to implement firebase queries